services:
    app:
        container_name: speedtest-app
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 80:80
            - 443:443
            - 5173:5173
            - 5174:5174
        environment:
            - XDEBUG_PORT=9000
            - XDEBUG_CLIENT_HOST=host.docker.internal
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - phpmyadmin
        networks:
            - ohmyfi

    mysql:
        image: mysql
        container_name: speedtest-mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ohmyfi_database
            MYSQL_PASSWORD: ohmyfi
            MYSQL_ROOT_PASSWORD: ohmyfi
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ohmyfi

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: speedtest-phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: ohmyfi
            MYSQL_ROOT_PASSWORD: ohmyfi
        networks:
            - ohmyfi

    postgres:
        image: postgres
        container_name: speedtest-postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ohmyfi_database
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ohmyfi
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ohmyfi

    pgadmin:
        image: dpage/pgadmin4
        container_name: speedtest-pgadmin4
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: root@dev.com
            PGADMIN_DEFAULT_PASSWORD: ohmyfi
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - ohmyfi

volumes:
    mysql_data:
    postgres_data:
    pgadmin_data:

networks:
    ohmyfi:
        driver: bridge